server:
  port: 8081

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&useUnicode=true&serverTimezone=Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.springcloud.order.pojo

myconfig:
  name: "1231312312"

#修改 Ribbon  的负载均衡机制(默认轮询)  IRule 实现类 均可配置
#product:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule